#!/usr/bin/env python3
"""Generate a real Second Brain you own — the production path (Mode B, SPEC §5.1).

This is the end-user entry point. It writes a brain scaffold into a path *you*
choose and bootstraps it as its **own** git repo, owned by you — distinct from the
devkit's throwaway ``sandbox/scratch/`` (Mode A, validation only).

    python3 tools/new_brain.py ~/my-brain

It shares the generator core with Mode A — ``generate()`` from ``generate.py`` —
so the scaffold you get is byte-identical to what the harness validates against the
golden (Mode A ≡ Mode B). Only the post-step differs: instead of a diff-and-discard,
Mode B does ``git init`` + first commit, so your brain's history *starts* here.

What it does:
  1. Refuse to nest inside an existing git repo (the repo-inside-a-repo antipattern,
     OQ-1) — pick a standalone path like ``~/my-brain``.
  2. ``generate()`` the scaffold (copy the template, seed the vault). Refuses a
     non-empty target unless ``--force`` (protects your data).
  3. ``git init`` + ``core.hooksPath .githooks`` (wires the embed hook) + a first
     commit (``--no-verify``: the scaffold ships pre-embedded ``test`` fixtures and
     git-ignores live vault vectors, so the initial commit never depends on a
     working embedder — you wire that up in first-time setup).

After it runs, follow the printed setup steps (``pip install -r requirements.txt``)
and start writing notes. The brain is yours; the devkit never touches it again.

This is a devkit tool; it is never emitted into a brain.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate import generate  # noqa: E402

FIRST_COMMIT_MSG = "Initial Second Brain scaffold (generated by second-brain-devkit)"


def enclosing_git_repo(location: Path) -> Path | None:
    """Toplevel of the git repo that would *contain* ``location``, or None.

    Checks the location's parent (the directory the brain would be created in), so
    the answer is independent of any ``.git`` the target itself may already hold —
    it purely asks "is this spot already under version control?". A non-None result
    means creating the brain here would nest one repo inside another (OQ-1).
    """
    start = location.parent
    while not start.exists():
        start = start.parent
    result = subprocess.run(
        ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        return Path(result.stdout.strip())
    return None


def _git(target: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(
        ["git", "-C", str(target), *args], capture_output=True, text=True,
    )
    if check and result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"new_brain: `git {' '.join(args)}` failed in {target}")
    return result


def bootstrap_git(target: Path) -> None:
    """Make ``target`` its own git repo: init + first commit + wire hooks."""
    _git(target, "init", "-q")
    _git(target, "add", "-A")
    # Commit the scaffold BEFORE wiring core.hooksPath, so neither the embed
    # pre-commit nor the hydrate post-commit fires on generation — they need the
    # embedder / sqlite-vec and would create derived artifacts (a brain.db) in the
    # freshly-generated tree. --no-verify is belt-and-suspenders (no hooks are
    # active yet). The user's later note commits use both hooks.
    _git(target, "commit", "-q", "--no-verify", "-m", FIRST_COMMIT_MSG)
    _git(target, "config", "core.hooksPath", ".githooks")


def new_brain(target, *, force: bool = False) -> Path:
    """Generate a brain at ``target`` and bootstrap it as its own repo."""
    target = Path(target).resolve()

    enclosing = enclosing_git_repo(target)
    if enclosing is not None:
        raise SystemExit(
            f"new_brain: refusing to create a brain inside the git repo at "
            f"{enclosing} — a brain must be its own top-level repo (OQ-1). "
            f"Choose a standalone path (e.g. ~/my-brain)."
        )

    generate(target, force=force)
    bootstrap_git(target)
    return target


def _print_next_steps(target: Path) -> None:
    print(f"\n✅ new brain at {target}")
    print("   next steps:")
    print(f"     cd {target}")
    print("     pip install -r requirements.txt   # embed pipeline deps")
    print("     python3 scripts/self_test.py      # confirm the pipeline is wired")
    print("   then start writing notes under vault/ and commit — the hook embeds them.")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        description="Generate a Second Brain you own (Mode B, production).",
    )
    ap.add_argument("target", help="where to create the brain (e.g. ~/my-brain)")
    ap.add_argument(
        "--force", action="store_true",
        help="overwrite a non-empty target (default: refuse, to protect data)",
    )
    args = ap.parse_args(argv)

    out = new_brain(args.target, force=args.force)
    _print_next_steps(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
