#!/usr/bin/env python3
"""Non-destructively upgrade an existing brain's tooling from this devkit (G4).

``create_second_brain.py`` can only *create* a brain (it refuses a non-empty target), so once a
brain is generated and filled with notes there is no supported way to pull in later
devkit improvements — new scripts, bug fixes, WAL, the MCP server — short of delete +
regenerate, which destroys the vault and git history. This closes that gap.

What it does:
  • Re-emits the **tooling** a brain ships — ``scripts/``, ``skill/``, ``.githooks/``,
    ``requirements*.txt``, ``tests/``, ``seeds/`` … — from the tracked ``template/``
    tree, picking up whatever the manifest now emits (so a new file like
    ``scripts/mcp_server.py`` is added automatically).
  • **``README.md`` is a managed block, not a wholesale copy (task #9).** A brain's
    README is a hybrid: the devkit owns the region between its ``<!-- BEGIN/END
    generated … -->`` markers, the user owns everything outside. So the README is
    **spliced** — the fresh devkit body replaces the marked block while the user's
    preamble/appendix are preserved byte-for-byte. A README with no markers (the user
    took full ownership) or only one marker (malformed) is left untouched and reported
    SKIP. See docs/readme-managed-block.md.
  • **Never touches your data:** ``vault/`` (notes), ``data/`` (cache), ``config/``
    (backend choice), or the personalizable ``CLAUDE.md`` / ``GEMINI.md`` — and never
    rewrites history.
  • **Dry-run by default** (shows NEW / CHANGED / preserved). ``--apply`` writes the
    files and records a single, git-revertable commit in the brain's own repo.

    python3 tools/update_brain.py ~/my-brain            # preview
    python3 tools/update_brain.py ~/my-brain --apply     # write + commit

Limits (MVP): additive — it adds/updates tooling but never *deletes* a file the devkit
no longer emits, and it can't tell a user-edited tooling file from an old version
(everything is git-revertable, and ``--apply`` refuses a dirty tree so the update lands
as an isolated commit). This is a devkit tool; it is never emitted into a brain.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = REPO_ROOT / "template"

# Reuse the emitted brain's marked-block splice helper (task #10) rather than
# duplicating the logic — the same primitive install_skill.py --nudge uses.
# Importing from the tracked template/ tree must not drop __pycache__/*.pyc into it
# (that would pollute the byte-exact template — and get copied into a brain).
sys.dont_write_bytecode = True
sys.path.insert(0, str(TEMPLATE / "scripts"))
try:
    from marked_block import MarkedBlockError, has_block, splice_block
except ModuleNotFoundError:  # template/ not built yet
    raise SystemExit(
        "update_brain: cannot import marked_block from template/scripts — "
        "run build_template.py first."
    )

# User territory — re-emitting these could clobber notes, the cache, the chosen
# backend, or personal memory. Never written. (vault/ isn't in template/ anyway.)
PRESERVE_DIRS = ("vault/", "data/", "config/")
PRESERVE_FILES = ("CLAUDE.md", "GEMINI.md")

# README.md is a hybrid (task #9): the devkit owns the block between these markers
# and regenerates it; the user owns everything outside. So instead of re-emitting
# the README wholesale (which clobbers the user's own preamble/appendix), we splice
# the fresh devkit body into the brain's *existing* markers. The strings must match
# the markers shipped in template/README.md byte-for-byte.
README = "README.md"
README_BEGIN = ("<!-- BEGIN generated by second-brain-devkit: do not edit inside; "
                "regenerated by update_brain.py. Put your own notes outside these markers. -->")
README_END = "<!-- END generated by second-brain-devkit -->"


def _is_preserved(rel: str) -> bool:
    return rel in PRESERVE_FILES or rel.startswith(PRESERVE_DIRS)


def _git(brain: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    r = subprocess.run(["git", "-C", str(brain), *args], capture_output=True, text=True)
    if check and r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit(f"update_brain: `git {' '.join(args)}` failed in {brain}")
    return r


def _differs(src: Path, dst: Path) -> str:
    """Classify src vs dst: 'new' | 'changed' | 'same' (symlink- and mode-aware)."""
    if not dst.exists() and not dst.is_symlink():
        return "new"
    if src.is_symlink() or dst.is_symlink():
        s = os.readlink(src) if src.is_symlink() else None
        d = os.readlink(dst) if dst.is_symlink() else None
        return "same" if s == d else "changed"
    if src.read_bytes() != dst.read_bytes():
        return "changed"
    return "same"


def _write(src: Path, dst: Path) -> None:
    """Replace dst with src, preserving symlinks and modes."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    if src.is_symlink():
        os.symlink(os.readlink(src), dst)
    else:
        shutil.copy2(src, dst)  # bytes + mode (exec bits)


def _looks_like_brain(brain: Path) -> bool:
    return (brain / "scripts" / "embedder.py").is_file() and (brain / ".git").exists()


def _managed_body(template_text: str) -> str:
    """The devkit body between the README markers, newline-trimmed."""
    after_begin = template_text.split(README_BEGIN, 1)[1]
    return after_begin.split(README_END, 1)[0].strip("\n")


def _readme_target(brain: Path, template_text: str) -> tuple[str, str | None, str]:
    """Decide how the brain's README should change by splicing the devkit's managed
    block into it, preserving the user's own space outside the markers.

    Returns ``(verdict, text, reason)``:
      ``new``     — brain has no README; ship the template whole (``text`` set).
      ``changed`` — splicing changes the managed block (``text`` = spliced result).
      ``same``    — already up to date (``text`` None).
      ``skip``    — README is user-owned or malformed; leave it (``text`` None, ``reason`` set).
    """
    if not has_block(template_text, README_BEGIN, README_END):
        raise SystemExit("update_brain: template README lacks the managed-block markers "
                         "— rebuild template/ (build_template.py).")
    dst = brain / README
    if not dst.exists():
        return ("new", template_text, "")  # no README yet → the whole template, markers and all
    existing = dst.read_text()
    # v1 manages exactly one region; refuse to guess a boundary among duplicates.
    if existing.count(README_BEGIN) > 1 or existing.count(README_END) > 1:
        return ("skip", None, "multiple devkit markers — left untouched (v1 manages one region)")
    try:
        present = has_block(existing, README_BEGIN, README_END)
    except MarkedBlockError:
        return ("skip", None, "one marker without its partner — left untouched")
    if not present:
        return ("skip", None, "no devkit markers — README is user-owned, left untouched")
    spliced = splice_block(existing, README_BEGIN, README_END, _managed_body(template_text))
    if spliced == existing:
        return ("same", None, "")
    return ("changed", spliced, "")


def plan(brain: Path) -> tuple[list[str], list[str], list[tuple[str, str]]]:
    """Return (new, changed, skipped) — tooling paths (rel), skipping preserved files.

    ``skipped`` carries ``(rel, reason)`` for files intentionally left alone (today
    only a user-owned/malformed README); preserved data files are not listed here.
    """
    if not TEMPLATE.is_dir():
        raise SystemExit(f"update_brain: no template at {TEMPLATE} — run build_template.py")
    new: list[str] = []
    changed: list[str] = []
    skipped: list[tuple[str, str]] = []
    for src in sorted(TEMPLATE.rglob("*")):
        if src.is_dir() and not src.is_symlink():
            continue
        rel = src.relative_to(TEMPLATE).as_posix()
        if _is_preserved(rel):
            continue
        if rel == README:
            verdict, _, reason = _readme_target(brain, src.read_text())
            if verdict == "skip":
                skipped.append((rel, reason))
            elif verdict in ("new", "changed"):
                (new if verdict == "new" else changed).append(rel)
            continue
        verdict = _differs(src, brain / rel)
        if verdict == "new":
            new.append(rel)
        elif verdict == "changed":
            changed.append(rel)
    return new, changed, skipped


def update_brain(target, *, apply: bool = False) -> int:
    brain = Path(target).expanduser().resolve()
    if not brain.is_dir():
        raise SystemExit(f"update_brain: {brain} is not a directory")
    if brain == REPO_ROOT:
        raise SystemExit("update_brain: that's the devkit itself, not a brain")
    if not _looks_like_brain(brain):
        raise SystemExit(
            f"update_brain: {brain} doesn't look like a generated brain "
            "(needs scripts/embedder.py and its own .git)"
        )

    new, changed, skipped = plan(brain)
    devkit_sha = _git(REPO_ROOT, "rev-parse", "--short", "HEAD", check=False).stdout.strip()

    print(f"update_brain: {brain}")
    if devkit_sha:
        print(f"  from devkit {devkit_sha}")
    print()
    for rel in new:
        print(f"  NEW      {rel}")
    for rel in changed:
        print(f"  CHANGED  {rel}")
    for rel, reason in skipped:
        print(f"  SKIP     {rel} — {reason}")
    print(f"\npreserved (never touched): vault/, data/, config/, CLAUDE.md, "
          "GEMINI.md, git history")

    # Migration notice (#30). These files define the *embed input* — what a note's vector is
    # computed over. If one of them changes, every existing vector was produced by the OLD
    # definition, but this tool never re-embeds (vault/ + data/ are preserved). Search still
    # works, so the staleness is silent. Tell the user to re-embed once; doctor --repair does it.
    EMBED_INPUT_FILES = {"scripts/note_view.py", "scripts/embedder.py"}
    view_changed = sorted(EMBED_INPUT_FILES.intersection(new + changed))
    if view_changed:
        print(f"\n⚠  MIGRATION — this update changes how notes embed ({', '.join(view_changed)}).")
        print("   Your existing vectors were built with the previous definition and are now")
        print("   STALE (search still works, but they no longer match what notes would embed to).")
        print("   Re-embed once after applying:  python3 scripts/doctor.py --repair")
        print("   (doctor also reports the staleness on its own — this is just the heads-up.)")

    if not (new or changed):
        print("\n✅ already up to date — nothing to do.")
        return 0

    if not apply:
        print(f"\nDry run — re-run with --apply to write {len(new) + len(changed)} "
              "file(s) and commit them in the brain.")
        return 0

    # --apply: refuse a dirty tree so the update lands as an isolated, revertable commit.
    if _git(brain, "status", "--porcelain").stdout.strip():
        raise SystemExit(
            "update_brain: brain has uncommitted changes — commit or stash them first, "
            "so this update lands as its own commit."
        )

    for rel in new + changed:
        if rel == README:
            # Splice the fresh devkit body into the brain's existing markers,
            # keeping the user's preamble/appendix byte-for-byte.
            _, text, _ = _readme_target(brain, (TEMPLATE / rel).read_text())
            (brain / rel).write_text(text)
        else:
            _write(TEMPLATE / rel, brain / rel)
        print(f"  wrote {rel}")

    _git(brain, "add", "--", *(new + changed))
    msg = "chore: update tooling from second-brain-devkit"
    if devkit_sha:
        msg += f" ({devkit_sha})"
    # --no-verify: this is tooling, not a note commit; skip the embed/line-count hook.
    _git(brain, "commit", "-q", "--no-verify", "-m", msg)
    head = _git(brain, "rev-parse", "--short", "HEAD").stdout.strip()
    print(f"\n✅ updated {len(new) + len(changed)} file(s); committed {head} in {brain}")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        description="Non-destructively upgrade an existing brain's tooling (G4).",
    )
    ap.add_argument("target", help="path to an existing brain (e.g. ~/my-brain)")
    ap.add_argument("--apply", action="store_true",
                    help="write the files and commit (default: dry-run preview)")
    args = ap.parse_args(argv)
    return update_brain(args.target, apply=args.apply)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
